/* Generated from 'RTableCreate02.nrx' 17 Jul 2012 16:25:44 [v3.01] */
/* Options: Binary Comments Compact Crossref Decimal Format Java Replace Symbols Trace2 UTF8 Verbose3 */

/* NetRexx */








public class RTableCreate02{
 private static final java.lang.String $0="RTableCreate02.nrx";
 /* properties indirect constant */
 private java.lang.String addressDDL=""+" "+" create table Address"+" "+" ("+" "+"   addrID     integer     primary key generated by default as identity,"+" "+"   addrStreet varchar(50) not null,"+" "+"   addrCity   varchar(50) not null,"+" "+"   addrState  char(2)     not null,"+" "+"   addrZip    char(10)    not null"+" "+" )";
 
 
 
 
 
 
 
 
 private java.lang.String driver="org.apache.derby.jdbc.EmbeddedDriver";
 private java.lang.String dbName="db/jdbcDemoDB";
 
 /* properties indirect */
 private java.lang.String connectionURL;
 private java.sql.Connection conn;
 private java.sql.Statement sqlStatement;

 
 
 public RTableCreate02(){super();
  return;
  }

 
 public void createTable(){
  java.sql.SQLException sex=null;
  java.lang.ClassNotFoundException ex=null;
  {try{
   java.lang.Class.forName(getDriver());
   setConnectionURL("jdbc:derby:"+getDbName()+";"+"create=true");
   setConn(java.sql.DriverManager.getConnection(getConnectionURL()));
   setSqlStatement(getConn().createStatement());
   netrexx.lang.RexxIO.Say("Creating table");
   getSqlStatement().execute(getAddressDDL());
   netrexx.lang.RexxIO.Say("Table cration complete");
   getSqlStatement().close();
   getConn().close();
   {try{
    // In embedded mode, an application should shut down Derby.
    // Shutdown throws the XJ015 exception to confirm success.
    setConnectionURL("jdbc:derby:"+";"+"shutdown=true");
    java.sql.DriverManager.getConnection(getConnectionURL());
   }
   catch (java.sql.SQLException $1){sex=$1;
    if (sex.getSQLState().equals((java.lang.Object)"XJ015")) 
     {
      netrexx.lang.RexxIO.Say("Database shut down normally");
     }
    else 
     {
      netrexx.lang.RexxIO.Say("Database did not shut down normally");
      throw sex;
     }
   }}
  }
  catch (java.sql.SQLException $2){sex=$2;
   sex.printStackTrace();
  }
  catch (java.lang.ClassNotFoundException $3){ex=$3;
   ex.printStackTrace();
  }}
  return;
  }

 
 public static void main(java.lang.String args[]){
  RTableCreate02 db;
  db=new RTableCreate02();
  db.createTable();
  return;
  }
 
 public java.lang.String getAddressDDL(){return addressDDL;}
 
 public java.lang.String getDriver(){return driver;}
 
 public java.lang.String getDbName(){return dbName;}
 
 public java.lang.String getConnectionURL(){return connectionURL;}
 
 public void setConnectionURL(java.lang.String $4){connectionURL=$4;return;}
 
 public java.sql.Connection getConn(){return conn;}
 
 public void setConn(java.sql.Connection $5){conn=$5;return;}
 
 public java.sql.Statement getSqlStatement(){return sqlStatement;}
 
 public void setSqlStatement(java.sql.Statement $6){sqlStatement=$6;return;}
 }
