/* Generated from 'RTableCreate01.nrx' 17 Jul 2012 16:25:44 [v3.01] */
/* Options: Binary Comments Compact Crossref Decimal Format Java Replace Symbols Trace2 UTF8 Verbose3 */

/* NetRexx */








public class RTableCreate01{
 private static final java.lang.String $0="RTableCreate01.nrx";
 /* properties private constant */
 private static final java.lang.String addressDDL=""+" "+" create table Address"+" "+" ("+" "+"   addrID     integer     primary key generated by default as identity,"+" "+"   addrStreet varchar(50) not null,"+" "+"   addrCity   varchar(50) not null,"+" "+"   addrState  char(2)     not null,"+" "+"   addrZip    char(10)    not null"+" "+" )";
 
 
 
 
 
 
 
 
 private static final java.lang.String driver="org.apache.derby.jdbc.EmbeddedDriver";
 private static final java.lang.String dbName="db/rosetta_code";

 
 
 public static void createTable(){
  java.lang.String connectionURL=null;
  java.sql.Connection conn=null;
  java.sql.Statement sqlStatement=null;
  java.sql.SQLException sex=null;
  java.lang.ClassNotFoundException ex=null;
  
  
  
  {try{
   java.lang.Class.forName(driver);
   connectionURL="jdbc:derby:"+dbName+";"+"create=true";
   conn=java.sql.DriverManager.getConnection(connectionURL);
   sqlStatement=conn.createStatement();
   netrexx.lang.RexxIO.Say("Creating table");
   sqlStatement.execute(addressDDL);
   netrexx.lang.RexxIO.Say("Table cration complete");
   sqlStatement.close();
   conn.close();
   {try{
    // In embedded mode, an application should shut down Derby.
    // Shutdown throws the XJ015 exception to confirm success.
    connectionURL="jdbc:derby:"+";"+"shutdown=true";
    java.sql.DriverManager.getConnection(connectionURL);
   }
   catch (java.sql.SQLException $1){sex=$1;
    if (sex.getSQLState().equals((java.lang.Object)"XJ015")) 
     {
      netrexx.lang.RexxIO.Say("Database shut down normally");
     }
    else 
     {
      netrexx.lang.RexxIO.Say("Database did not shut down normally");
      throw sex;
     }
   }}
  }
  catch (java.sql.SQLException $2){sex=$2;
   sex.printStackTrace();
  }
  catch (java.lang.ClassNotFoundException $3){ex=$3;
   ex.printStackTrace();
  }}
  return;
  }

 
 public static void main(java.lang.String args[]){
  createTable();
  return;
  }
 
 private RTableCreate01(){return;}
 }
