/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RJNIDemo */

#ifndef _Included_RJNIDemo
#define _Included_RJNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RJNIDemo
 * Method:    jniFunc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_RJNIDemo_jniFunc
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
